#!/usr/bin/env bash

# Get script execution directory
BASE_DIRECTORY="$( cd -P "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"

# Get command
COMMAND="${1}"

# Process command
case "${COMMAND}" in
    "migrate")
        "${BASE_DIRECTORY}/tools/scripts/flyway/migrate.sh"
        ;;

    "clean")
        "${BASE_DIRECTORY}/tools/scripts/flyway/clean.sh"
        ;;

    "reset")
        "${BASE_DIRECTORY}/tools/scripts/flyway/clean.sh"
        "${BASE_DIRECTORY}/tools/scripts/flyway/migrate.sh"
        ;;

    "models")
        "${BASE_DIRECTORY}/tools/scripts/models/generate.sh"
        ;;
    *)
        echo "Unsupported command: \"migrate\", \"clean\", and \"models\" are the only valid options"
        echo "Usage: ./migrations/migrate <clean | migrate | reset | models>"

esac
